version: "3.7"

services:
    app:
        build:
            context: .
        image: bhatsubhas/flasky:latest
        environment:
            - APP_PORT=8080
            - FLASK_ENV=production
        ports:
            - "8080:8080"